name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy: 
    node-version: [23.x]
  steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
        name: install modules
        run: npm install 

        name: unit test
        run: npm run test
        
        name: build project
        run: npm run build


